user-packages = [
  "firefox",
  "discord",
  "wget",
  "spotify",
  "xorg.xrdb",
  "htop",
  "rxvt-unicode",
  "xorg.xeyes",
  "fortune",
  "easyeffects",
  "fzf",
  "evince",
  "google-chrome",
  "feh",
  "gnome.gnome-screenshot",
  "wl-clipboard",
  "pavucontrol",
]

system-packages = [
  "lightdm",
  "linuxKernel.kernels.linux_xanmod",
  "vim",
  "xfce.thunar",
  "docker",
  "unstable.fish",
]

fonts = [
  "source-code-pro",
  "roboto-mono",
  "hack-font",
]

shells = [
  "unstable.fish",
  "dash",
]

development = [
  "shellcheck",
  "rustup",
  "gcc",
  "sublime3",
  "gnumake",
  "nil",
  "nixpkgs-fmt",
  "vscode",
  "dconf2nix",
  "terraform",
  "git",
  "azure-cli",
  "awscli2",
  "dotnet-sdk",
  "yarn",
  "openssl",
  "openssl.dev",
]

emulation = [
  "qemu",
  "libvirt",
  "edk2",
  "virt-manager",
  "dnsmasq",
  "ebtables",
  "pciutils",
]
